insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Evvy Walkowski', 'Schiller', '2017-09-11');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Ginnifer Abbess', 'Rowland', '2008-07-06');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Murielle Batham', 'Kennedy', '2003-10-01');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Mikaela Busch', 'Westend', '2000-02-12');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Rod Deboo', 'Upham', '2014-05-15');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Woodie Vaughten', 'Mitchell', '2014-09-25');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Jaye Chadwick', 'Wayridge', '2011-01-26');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Weidar Lampett', 'Coleman', '2007-09-21');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Beatrisa Capell', 'Canary', '2006-01-23');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Lauren Barzen', 'Basil', '2013-06-07');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Anselma Klauer', 'Springs', '2004-01-26');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Elwood Nucciotti', 'Roxbury', '2022-03-12');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Larine Dodgson', 'Independence', '2003-12-10');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Thane Maylott', 'Morning', '2007-10-01');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Tanney Mannion', 'Prairie Rose', '2018-08-17');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Isidor Styant', 'Golden Leaf', '2019-11-01');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Kaitlyn Beilby', 'Miller', '2021-01-14');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Rosene Tibols', 'Delaware', '2000-10-18');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Nanny Jeduch', 'Declaration', '2000-03-29');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Deloria Lippett', 'Nevada', '2001-09-14');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Wendie Sture', 'Oxford', '2014-11-08');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Raoul Margrem', 'Linden', '2000-05-09');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Lesya Childs', 'Cardinal', '2013-11-07');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Cindi Arboine', 'Melvin', '2017-03-02');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Fulton Wrack', 'Tennyson', '2011-12-27');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Berky Dyshart', 'Sauthoff', '2003-06-11');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Palmer Cuzen', 'Annamark', '2007-12-12');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Waite Rayhill', 'Golf View', '2016-07-16');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Kathye Fredi', 'Myrtle', '2012-05-26');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Bertie Maitland', 'Schmedeman', '2013-11-06');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Puff Revance', 'Mcbride', '2021-11-20');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Coleen Kitchingman', 'Dunning', '2012-09-21');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Randy Glanville', 'Rieder', '2019-07-10');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Henrik Dagless', 'Coleman', '2011-09-08');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Natal Grieveson', 'Huxley', '2006-10-20');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Darice Gauvin', 'Upham', '2003-05-06');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Lindy Syder', 'Dryden', '2011-12-18');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Padraic Antoons', 'Dawn', '2006-11-13');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Aloisia Lorens', 'John Wall', '2014-04-23');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Archer Branney', 'Thackeray', '2015-08-08');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Stephen Kyne', 'Golden Leaf', '2003-01-15');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Shandie Wonfar', 'Hooker', '2020-02-25');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Reade Ashtonhurst', 'Anhalt', '2007-11-03');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Tiebold Mays', 'Moulton', '2007-07-06');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Gaylene Warham', 'Haas', '2007-02-18');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Kendal Flewett', 'Ridgeway', '2010-11-05');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Gretel Bover', 'Boyd', '2012-01-15');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Sharon Martugin', 'Glendale', '2001-02-11');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Lemmy Rosser', 'Heath', '2016-01-04');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Dorita Ilott', 'Dunning', '2004-08-01');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Mickey Ionnidis', 'Forest Run', '2019-07-29');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Heidie Roulston', 'Holmberg', '2018-02-15');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Kathy Fliege', 'Village', '2014-06-24');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Isobel Castanho', 'Golf Course', '1999-07-23');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Stesha Guenther', 'Clemons', '2020-12-27');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Lanna Stonier', 'Steensland', '2012-02-23');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Robbin Gayle', 'Fieldstone', '2009-02-14');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Sergei Stuckes', 'Emmet', '2007-04-16');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Micky Geipel', 'Tennessee', '2010-11-02');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Lemar Ashton', 'Florence', '2002-10-17');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Karney Scutcheon', 'Canary', '2007-08-21');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Elayne Basini-Gazzi', 'Grover', '2011-01-05');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Ber McReath', 'Dwight', '2015-01-09');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Stephanie Rimes', 'Dixon', '2000-04-19');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Jeremias Tempest', 'Gina', '2015-02-11');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Ossie Spatig', 'Nova', '2021-06-30');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Theobald Penwell', 'Ilene', '2006-11-11');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Gideon Clingan', 'Eagle Crest', '2004-03-06');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Arlie Nansom', 'Buena Vista', '2010-03-11');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Walker Sibborn', 'Macpherson', '1999-07-20');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Maryl Wreight', 'Sommers', '2014-06-13');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Laurent Balmforth', 'Scoville', '2017-02-08');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Pattie Briereton', 'Division', '2018-06-24');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Marian Glencros', 'Arizona', '2001-05-15');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Meggi Stenyng', 'Dapin', '2019-01-07');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Paxton Olesen', 'Old Shore', '2016-09-13');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Dorothea Harriskine', 'Grasskamp', '2013-08-28');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Sanderson Yanukhin', 'Little Fleur', '2014-07-19');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Bethina Lamplough', 'Homewood', '2016-06-17');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Mike Castard', 'Kinsman', '2000-04-10');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Yankee Audry', 'Doe Crossing', '2013-04-14');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Bartie Garces', 'Novick', '2015-02-20');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Guenevere Bamborough', 'Lyons', '2011-05-14');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Belita Gare', 'Forster', '2020-02-23');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Lew Tumasian', 'Schmedeman', '2020-10-19');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Stanleigh Dorran', 'Meadow Vale', '2005-10-09');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Alanna D''Onisi', 'Texas', '2014-05-23');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Charline Braycotton', 'Paget', '2018-07-06');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Myriam Studart', 'Pond', '2020-01-18');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Johnnie Kulic', 'Mayfield', '2017-07-19');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Lila Meas', 'Arkansas', '2021-10-01');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Emalia Brigg', 'Pleasure', '2020-05-01');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Halette Maher', 'Sage', '2008-05-29');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Andrew Chrystie', 'Oak', '1999-12-10');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Kennedy Benezet', 'West', '2018-08-19');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Doe Stubbert', 'Burning Wood', '2015-04-20');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Shanna Rolfs', 'Amoth', '2021-12-12');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Ilyse Trotton', 'Mcguire', '2018-01-28');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Rafe McAirt', 'Lakeland', '2013-06-12');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Upton Chalcraft', 'Valley Edge', '2019-09-13');
