insert into trenes (modelo, capacidad) values ('TrailBlazer', 1);
insert into trenes (modelo, capacidad) values ('Jetta', 2);
insert into trenes (modelo, capacidad) values ('Escalade EXT', 3);
insert into trenes (modelo, capacidad) values ('Eclipse', 4);
insert into trenes (modelo, capacidad) values ('X5 M', 5);
insert into trenes (modelo, capacidad) values ('Murciélago', 6);
insert into trenes (modelo, capacidad) values ('9000', 7);
insert into trenes (modelo, capacidad) values ('Explorer', 8);
insert into trenes (modelo, capacidad) values ('Contour', 9);
insert into trenes (modelo, capacidad) values ('Fiesta', 10);
insert into trenes (modelo, capacidad) values ('Monte Carlo', 11);
insert into trenes (modelo, capacidad) values ('Z8', 12);
insert into trenes (modelo, capacidad) values ('CL-Class', 13);
insert into trenes (modelo, capacidad) values ('300ZX', 14);
insert into trenes (modelo, capacidad) values ('Skyhawk', 15);
insert into trenes (modelo, capacidad) values ('X5', 16);
insert into trenes (modelo, capacidad) values ('Prizm', 17);
insert into trenes (modelo, capacidad) values ('NSX', 18);
insert into trenes (modelo, capacidad) values ('Sierra 2500', 19);
insert into trenes (modelo, capacidad) values ('6 Series', 20);
insert into trenes (modelo, capacidad) values ('Taurus', 21);
insert into trenes (modelo, capacidad) values ('S-Series', 22);
insert into trenes (modelo, capacidad) values ('Q7', 23);
insert into trenes (modelo, capacidad) values ('M', 24);
insert into trenes (modelo, capacidad) values ('CTS', 25);
insert into trenes (modelo, capacidad) values ('QX', 26);
insert into trenes (modelo, capacidad) values ('Spyder', 27);
insert into trenes (modelo, capacidad) values ('Century', 28);
insert into trenes (modelo, capacidad) values ('Freelander', 29);
insert into trenes (modelo, capacidad) values ('Phantom', 30);
insert into trenes (modelo, capacidad) values ('M', 31);
insert into trenes (modelo, capacidad) values ('Escalade ESV', 32);
insert into trenes (modelo, capacidad) values ('FX', 33);
insert into trenes (modelo, capacidad) values ('Festiva', 34);
insert into trenes (modelo, capacidad) values ('A8', 35);
insert into trenes (modelo, capacidad) values ('GTO', 36);
insert into trenes (modelo, capacidad) values ('Mazda6', 37);
insert into trenes (modelo, capacidad) values ('Ciera', 38);
insert into trenes (modelo, capacidad) values ('Bonneville', 39);
insert into trenes (modelo, capacidad) values ('New Beetle', 40);
insert into trenes (modelo, capacidad) values ('MX-5', 41);
insert into trenes (modelo, capacidad) values ('4Runner', 42);
insert into trenes (modelo, capacidad) values ('B-Series Plus', 43);
insert into trenes (modelo, capacidad) values ('Mirage', 44);
insert into trenes (modelo, capacidad) values ('New Beetle', 45);
insert into trenes (modelo, capacidad) values ('960', 46);
insert into trenes (modelo, capacidad) values ('Fusion', 47);
insert into trenes (modelo, capacidad) values ('Ranger', 48);
insert into trenes (modelo, capacidad) values ('G', 49);
insert into trenes (modelo, capacidad) values ('Mirage', 50);
insert into trenes (modelo, capacidad) values ('Camaro', 51);
insert into trenes (modelo, capacidad) values ('Escort', 52);
insert into trenes (modelo, capacidad) values ('Town Car', 53);
insert into trenes (modelo, capacidad) values ('4Runner', 54);
insert into trenes (modelo, capacidad) values ('1500', 55);
insert into trenes (modelo, capacidad) values ('Countryman', 56);
insert into trenes (modelo, capacidad) values ('GLK-Class', 57);
insert into trenes (modelo, capacidad) values ('Equinox', 58);
insert into trenes (modelo, capacidad) values ('HHR', 59);
insert into trenes (modelo, capacidad) values ('Magnum', 60);
insert into trenes (modelo, capacidad) values ('Golf', 61);
insert into trenes (modelo, capacidad) values ('Swift', 62);
insert into trenes (modelo, capacidad) values ('Corrado', 63);
insert into trenes (modelo, capacidad) values ('CX-5', 64);
insert into trenes (modelo, capacidad) values ('Clubman', 65);
insert into trenes (modelo, capacidad) values ('Sonoma Club Coupe', 66);
insert into trenes (modelo, capacidad) values ('Sonic', 67);
insert into trenes (modelo, capacidad) values ('E-Series', 68);
insert into trenes (modelo, capacidad) values ('Legacy', 69);
insert into trenes (modelo, capacidad) values ('Discovery', 70);
insert into trenes (modelo, capacidad) values ('Riviera', 71);
insert into trenes (modelo, capacidad) values ('Sonata', 72);
insert into trenes (modelo, capacidad) values ('Mazda6', 73);
insert into trenes (modelo, capacidad) values ('Vandura 1500', 74);
insert into trenes (modelo, capacidad) values ('RX Hybrid', 75);
insert into trenes (modelo, capacidad) values ('Galant', 76);
insert into trenes (modelo, capacidad) values ('Navigator', 77);
insert into trenes (modelo, capacidad) values ('Suburban 1500', 78);
insert into trenes (modelo, capacidad) values ('Amigo', 79);
insert into trenes (modelo, capacidad) values ('Accord Crosstour', 80);
insert into trenes (modelo, capacidad) values ('Altima', 81);
insert into trenes (modelo, capacidad) values ('Tribute', 82);
insert into trenes (modelo, capacidad) values ('GTI', 83);
insert into trenes (modelo, capacidad) values ('Titan', 84);
insert into trenes (modelo, capacidad) values ('Contour', 85);
insert into trenes (modelo, capacidad) values ('240SX', 86);
insert into trenes (modelo, capacidad) values ('Thunderbird', 87);
insert into trenes (modelo, capacidad) values ('G-Series G20', 88);
insert into trenes (modelo, capacidad) values ('3000GT', 89);
insert into trenes (modelo, capacidad) values ('Explorer Sport Trac', 90);
insert into trenes (modelo, capacidad) values ('Regal', 91);
insert into trenes (modelo, capacidad) values ('Colt', 92);
insert into trenes (modelo, capacidad) values ('XK', 93);
insert into trenes (modelo, capacidad) values ('Astro', 94);
insert into trenes (modelo, capacidad) values ('Suburban 2500', 95);
insert into trenes (modelo, capacidad) values ('Town & Country', 96);
insert into trenes (modelo, capacidad) values ('Cube', 97);
insert into trenes (modelo, capacidad) values ('Camry', 98);
insert into trenes (modelo, capacidad) values ('Millenia', 99);
insert into trenes (modelo, capacidad) values ('Mazda6', 100);
